### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by CSQianDong** [pickou/ccf_human_or_robot#1]
我是一名大三的学生，我想学习一下您对这个题目的思路，请问您数据集有没有保留？万分感谢

**Comment by pickou** [comment]
链接: https://pan.baidu.com/s/1hsNBc92 密码: 9xg6。
这是初赛的，我这个思路就是特征提取加lightgbm,技术含量不高，后面整理也做得不够好，
然后内存可能要求比较大，不知道你机器能不能跑起来。
